### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by themorfeus** [M-Fatah/texture_maker#2]
Please add a license so that people can use it in their projects under terms that suit the creator. I'd suggest using a tool made by Github specifically for the purpose of choosing licenses: https://choosealicense.com/

I love the tool, but if no license is specified it defaults to 'All Rights Reserved', which means that noone can legally use it.

Thanks! The tool looks great, by the way!!

**Comment by M-Fatah** [comment]
Hey, Sure, I will add the MIT license. Thanks
